version: "3.9"
services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - .:/discord-pmbot
    ports:
      - "3000:3000"
